channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - notebook=6.0.3
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pip:
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - bash_kernel==0.7.1
